/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 03-Feb-2022 00:40:40
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021a\extern\include\tmwtypes.h 
 */
const int BL = 11;
const real64_T B[11] = {
   0.004960022027719, 0.005577211783262, -0.01899219729718,  -0.1066292338452,
    -0.2272326527617,   0.7195743880616,  -0.2272326527617,  -0.1066292338452,
   -0.01899219729718, 0.005577211783262, 0.004960022027719
};
