/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 02-Feb-2022 20:59:27
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021a\extern\include\tmwtypes.h 
 */
const int BL = 11;
const real64_T B[11] = {
  -0.003588450729125,-0.007823258658934, -0.01909630127682, -0.03342972970083,
   -0.04525844907547,   0.9466195745567, -0.04525844907547, -0.03342972970083,
   -0.01909630127682,-0.007823258658934,-0.003588450729125
};
