/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 02-Feb-2022 21:00:35
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021a\extern\include\tmwtypes.h 
 */
const int BL = 11;
const real64_T B[11] = {
   -0.00157134085164,-0.003316600649128,-0.007897594410545, -0.01358572431153,
   -0.01820234553821,   0.9784620883205, -0.01820234553821, -0.01358572431153,
  -0.007897594410545,-0.003316600649128, -0.00157134085164
};
