/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 02-Feb-2022 21:01:52
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021a\extern\include\tmwtypes.h 
 */
const int BL = 11;
const real64_T B[11] = {
  -0.004105039038344, -0.01307209432777, -0.04073587685012, -0.08334283509398,
    -0.1231655988038,   0.8568168294591,  -0.1231655988038, -0.08334283509398,
   -0.04073587685012, -0.01307209432777,-0.004105039038344
};
