/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 02-Feb-2022 21:50:47
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021a\extern\include\tmwtypes.h 
 */
const int BL = 11;
const real64_T B[11] = {
  -0.004103589675521,-0.009106607977227, -0.02252740769763, -0.03980426270555,
   -0.05418484133162,    0.936190063956, -0.05418484133162, -0.03980426270555,
   -0.02252740769763,-0.009106607977227,-0.004103589675521
};
