/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 14-Jun-2022 16:22:29
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 16
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021a\extern\include\tmwtypes.h 
 */
const int BL = 16;
const real64_T B[16] = {
  -0.003471276445115, -0.00485120373109,-0.004245630750047, 0.008891029945241,
    0.04423731627554,   0.1002331073527,   0.1601002781948,   0.1991063791579,
     0.1991063791579,   0.1601002781948,   0.1002331073527,  0.04423731627554,
   0.008891029945241,-0.004245630750047, -0.00485120373109,-0.003471276445115
};
